-- Code by Matthew Zuberbuhler & Karan Sharma --

CREATE TABLE users (
    userid INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(32) NOT NULL UNIQUE,
    email VARCHAR(256) NOT NULL,
    token VARCHAR(60) UNIQUE NOT NULL
) ENGINE INNODB;

CREATE TABLE tasks (
    userid INT UNSIGNED NOT NULL,
    taskid INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE  PRIMARY KEY,
    category VARCHAR(32) NOT NULL,
    title VARCHAR(80) NOT NULL,
    content VARCHAR(500) NOT NULL,
    due_date DATE NOT NULL,
    status int NOT NULL,
    FOREIGN KEY (userid) REFERENCES users (userid) ON DELETE CASCADE
) ENGINE INNODB;